export const START_CONTEST ="START_CONTEST";
export const END_CONTEST = "END_CONTEST";
export const START_MATCHMAKING = "START_MATCHMAKING";
export const END_MATCHMAKING = "END_MATCHMAKING";
export const OPPONENT_READY = "OPPONENT_READY";
export const OPPONENT_LEFT = "OPPONENT_LEFT";